services:
  auth-center:
    container_name: "${CONTAINER_NAME}"
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms128m -Xmx256m"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${CONFIG_DIR}:/app/config:ro
    networks:
      - infra-net

networks:
  infra-net:
    external: true
