server {
    listen 80;
    server_name auth.sillyarmor.com;

    location / {
        proxy_pass http://auth-center:8080;
	    proxy_cookie_path / "/; Domain=.sillyarmor.com"; # 暂时解决同类子域名 cookie 跨域的问题
    }
}
